/**
 * Offline English → Kashmiri lookup for tappable lesson translations (WAN-53).
 *
 * data/english_kashmiri_dictionary.json is generated by
 * scripts/buildEnglishDictionary.js from:
 *  - Kaeshir Database collected words (romanised + Perso-Arabic script); rows
 *    that spell a Hassan headword also carry its DSAL recording
 *  - Sheeba Hassan's Kashmiri-English dictionary (romanised, with audio)
 *  - optionally kashmirizabaan.com (Perso-Arabic script, no audio); left out
 *    by default so every popup entry has a transliteration and a recording
 * The normalisation and word-form rules here must match that script.
 */
import { tokenizeWithPhrases, type TextToken } from './dictionary';

export type EnglishDictionarySource = 'kaeshir' | 'hassan' | 'zabaan';

export interface KashmiriTranslation {
  kashmiri: string;
  script: 'roman' | 'arabic';
  /** Perso-Arabic spelling shown under the romanised one (Kaeshir entries). */
  scriptText?: string;
  partOfSpeech?: string;
  source: EnglishDictionarySource;
  /** DSAL audio id (Hassan entries, and Kaeshir entries merged with one). */
  audioId?: string;
}

export interface EnglishMatch {
  /** Normalised dictionary key that matched, e.g. "father". */
  key: string;
  translations: KashmiriTranslation[];
  isPhrase: boolean;
}

type RawEntry = [roman: string, arabic: string, pos: string, audioId: string];

interface RawDictionary {
  maxPhraseWords: number;
  stopwords: string[];
  entries: RawEntry[];
  index: Record<string, number[]>;
}

interface AudioManifest {
  bucket: string;
  prefix: string;
  uploaded: boolean;
  ids: string[];
}

let loaded: { raw: RawDictionary; stop: Set<string> } | null = null;

function load() {
  if (!loaded) {
    const raw = require('../../data/english_kashmiri_dictionary.json') as RawDictionary;
    loaded = { raw, stop: new Set(raw.stopwords) };
  }
  return loaded;
}

export function normalizeEnglish(text: string): string {
  return text
    .normalize('NFKC')
    .toLowerCase()
    .replace(/[’‘`]/g, "'")
    .replace(/[-‐–—/]/g, ' ')
    .replace(/[^a-z0-9' ]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^'+|'+$/g, '');
}

/** The word itself, then plausible dictionary forms (plural, past, -ing). */
function wordCandidates(key: string, stop: Set<string>): string[] {
  const out = [key];
  if (key.includes(' ') || key.length <= 3 || stop.has(key)) return out;
  if (key.endsWith("'s")) out.push(key.slice(0, -2));
  if (key.endsWith('ies')) out.push(`${key.slice(0, -3)}y`);
  if (key.endsWith('es')) out.push(key.slice(0, -2));
  if (key.endsWith('s') && !key.endsWith('ss')) out.push(key.slice(0, -1));
  if (key.endsWith('ied')) out.push(`${key.slice(0, -3)}y`);
  if (key.endsWith('ed')) out.push(key.slice(0, -2), key.slice(0, -1));
  if (key.endsWith('ing') && key.length > 5) out.push(key.slice(0, -3), `${key.slice(0, -3)}e`);
  return [...new Set(out)].filter((k) => k.length >= 3 && !stop.has(k));
}

function matchFor(key: string): EnglishMatch | null {
  const { raw } = load();
  const ids = raw.index[key];
  if (!ids) return null;
  return {
    key,
    isPhrase: key.includes(' '),
    translations: ids.map((id) => {
      const [roman, arabic, pos, audioId] = raw.entries[id];
      const common = { partOfSpeech: pos || undefined, audioId: audioId || undefined };
      if (roman && arabic) {
        return { ...common, kashmiri: roman, script: 'roman', scriptText: arabic, source: 'kaeshir' };
      }
      return roman
        ? { ...common, kashmiri: roman, script: 'roman', source: 'hassan' }
        : { ...common, kashmiri: arabic, script: 'arabic', source: 'zabaan' };
    }),
  };
}

export function lookupEnglish(word: string): EnglishMatch | null {
  const { stop } = load();
  for (const key of wordCandidates(normalizeEnglish(word), stop)) {
    const match = matchFor(key);
    if (match) return match;
  }
  return null;
}

const TOKEN_PATTERN = /[\p{L}\p{M}0-9'’-]+|[^\p{L}\p{M}0-9'’-]+/gu;

export function tokenizeEnglish(text: string): TextToken<EnglishMatch>[] {
  return tokenizeWithPhrases(text, {
    pattern: TOKEN_PATTERN,
    isWord: (raw) => /\p{L}/u.test(raw),
    maxPhraseWords: load().raw.maxPhraseWords,
    lookupPhrase: (span) => matchFor(normalizeEnglish(span)),
    lookupWord: lookupEnglish,
  });
}

// --- Audio ------------------------------------------------------------------

// Original source of the recordings. Used until the clips are uploaded to the
// course-audio bucket (scripts/uploadDictionaryAudio.js flips "uploaded").
const DSAL_AUDIO_BASE = 'https://dsal.uchicago.edu/dictionaries/hassan/audio/';

let audioManifest: { manifest: AudioManifest; ids: Set<string> } | null = null;

/** Candidate URLs for a pronunciation, best first. */
export function dictionaryAudioUrls(audioId: string): string[] {
  if (!audioManifest) {
    const manifest = require('../../data/dictionary_audio_manifest.json') as AudioManifest;
    audioManifest = { manifest, ids: new Set(manifest.ids) };
  }
  const { manifest, ids } = audioManifest;
  const urls: string[] = [];
  const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL;
  if (manifest.uploaded && supabaseUrl && ids.has(audioId)) {
    urls.push(`${supabaseUrl}/storage/v1/object/public/${manifest.bucket}/${manifest.prefix}${audioId}.mp3`);
  }
  urls.push(`${DSAL_AUDIO_BASE}${audioId}.mp3`);
  return urls;
}
